name: jue_jin_blog
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6
  dio: ^4.0.0-beta7
  common_utils: ^2.0.0
  fluttertoast: ^7.0.0
  pin_code_fields: ^6.1.0
  flutter_markdown: ^0.6.10
  image_picker: ^0.8.5+3
  wechat_assets_picker: ^7.3.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/mine_info/ic_bell_ring.png
    - lib/images/mine_info/ic_setting.png
    - lib/images/mine_info/ic_moon.png
    - lib/images/mine_info/empty_avatar_user.webp
    - lib/images/mine_info/ic_user_sign.webp
    - lib/images/mine_info/ic_user_bug.webp
    - lib/images/mine_info/ic_user_luck.webp
    - lib/images/mine_info/ic_user_change.webp
    - lib/images/mine_info/ic_user_course.png
    - lib/images/mine_info/ic_user_popularize.png
    - lib/images/mine_info/ic_user_creator.png
    - lib/images/mine_info/ic_user_pins.png
    - lib/images/mine_info/ic_user_history.png
    - lib/images/mine_info/ic_user_tag.png
    - lib/images/mine_info/ic_user_suggest.png
    - lib/images/mine_info/ic_user_resume.png
    - lib/images/login_register/ic_launcher.png
    - lib/images/login_register/account_x_ic_github.png
    - lib/images/login_register/base_ic_share_wechat.png
    - lib/images/login_register/ic_course_lock.webp
    - lib/images/oth/ic_user_empty.webp
    - lib/images/bottom_bar/tab_activity.webp
    - lib/images/bottom_bar/tab_home_normal.webp
    - lib/images/bottom_bar/tab_xiaoce_normal.webp
    - lib/images/bottom_bar/tab_find_normal.webp
    - lib/images/bottom_bar/tab_profile_normal.webp
    - lib/images/bottom_bar/tab_home.webp
    - lib/images/bottom_bar/tab_activity_press.webp
    - lib/images/bottom_bar/tab_find.webp
    - lib/images/bottom_bar/tab_xiaoce.webp
    - lib/images/bottom_bar/tab_profile.webp
    - lib/images/home_page/ic_live.png
    - lib/images/home_page/ic_live_36.png
    - lib/images/home_page/ic_calendar_unchecked.webp
    - lib/images/home_page/ic_good_author.webp
    - lib/images/empty/empty_list_icon.png
    - lib/images/home_page/ic_liked_un_selected.png
    - lib/images/home_page/ic_pins_comment.png
    - lib/images/home_page/bg_hot_rank1.webp
    - lib/images/home_page/bg_hot_rank2.webp
    - lib/images/home_page/bg_hot_rank3.webp
    - lib/asset/Spring.md
    - lib/images/hot_page/WeChat0bc1ceb0b11a45dc68620cc5447685ae.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
